import assert from "node:assert/strict";
import { test } from "node:test";

import { ASSET_KINDS } from "../../../../../shared/assetKinds.js";
import { classifyPlyHeader, parsePlyHeader } from "../../../../../shared/pointcloud/plyAssetKind.js";
import { detectAssetKind } from "./resourceKinds.js";

test("detectAssetKind prefers explicit asset kind", () => {
    assert.equal(detectAssetKind({ kind: "SPLAT", name: "model.glb" }), "splat");
});

test("detectAssetKind detects kind from resolved source URL", () => {
    assert.equal(
        detectAssetKind({ name: "asset-without-extension" }, { url: "https://example.test/model.pcd" }),
        "pointcloud"
    );
});

test("detectAssetKind detects Potree streaming entry files", () => {
    assert.equal(
        detectAssetKind({ name: "asset-without-extension" }, { url: "https://example.test/scan/metadata.json" }),
        "pointcloud-streaming"
    );
    assert.equal(detectAssetKind({ name: "cloud.js" }), "pointcloud-streaming");
});

test("detectAssetKind treats Potree zip uploads as streaming point clouds in admin", () => {
    assert.equal(detectAssetKind({ name: "converted-potree.zip" }), "pointcloud-streaming");
});

test("detectAssetKind treats gaussian splat formats as splat assets", () => {
    assert.equal(detectAssetKind({ name: "scan.ply" }), "splat");
    assert.equal(detectAssetKind({ name: "scan.spz" }), "splat");
});

test("detectAssetKind can explicitly treat ply as a classic point cloud", () => {
    assert.equal(detectAssetKind({ kind: "pointcloud", name: "scan.ply" }), "pointcloud");
});

test("PLY classifier treats CloudCompare style PLY as a classic point cloud", () => {
    const header = parsePlyHeader([
        "ply",
        "format ascii 1.0",
        "obj_info Generated by CloudCompare!",
        "element vertex 3",
        "property float x",
        "property float y",
        "property float z",
        "property uchar red",
        "property uchar green",
        "property uchar blue",
        "end_header",
    ].join("\n"));

    assert.equal(classifyPlyHeader(header), ASSET_KINDS.POINTCLOUD);
});

test("PLY classifier preserves Gaussian splat PLY files as splats", () => {
    const header = parsePlyHeader([
        "ply",
        "format binary_little_endian 1.0",
        "element vertex 1",
        "property float x",
        "property float y",
        "property float z",
        "property float f_dc_0",
        "property float f_dc_1",
        "property float f_dc_2",
        "property float opacity",
        "property float scale_0",
        "property float rot_0",
        "end_header",
    ].join("\n"));

    assert.equal(classifyPlyHeader(header), ASSET_KINDS.SPLAT);
});

test("detectAssetKind defaults to gltf for unknown sources", () => {
    assert.equal(detectAssetKind({ name: "unknown.asset" }), "gltf");
});
